// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class MinecraftProfileCape {
    "id": string;

    /**
     * ACTIVE or INACTIVE
     */
    "state": string;
    "url": string;
    "alias": string;

    /** Creates a new MinecraftProfileCape instance. */
    constructor($$source: Partial<MinecraftProfileCape> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("alias" in $$source)) {
            this["alias"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinecraftProfileCape instance from a string or object.
     */
    static createFrom($$source: any = {}): MinecraftProfileCape {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinecraftProfileCape($$parsedSource as Partial<MinecraftProfileCape>);
    }
}

export class MinecraftProfileSkin {
    "id": string;

    /**
     * ACTIVE or INACTIVE
     */
    "state": string;
    "url": string;
    "variant": string;

    /** Creates a new MinecraftProfileSkin instance. */
    constructor($$source: Partial<MinecraftProfileSkin> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("variant" in $$source)) {
            this["variant"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinecraftProfileSkin instance from a string or object.
     */
    static createFrom($$source: any = {}): MinecraftProfileSkin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinecraftProfileSkin($$parsedSource as Partial<MinecraftProfileSkin>);
    }
}

export class MinecraftVersionInfo {
    "id": string;
    "type": string;
    "releaseTime": string;
    "complianceLevel": number;

    /** Creates a new MinecraftVersionInfo instance. */
    constructor($$source: Partial<MinecraftVersionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("releaseTime" in $$source)) {
            this["releaseTime"] = "";
        }
        if (!("complianceLevel" in $$source)) {
            this["complianceLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinecraftVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MinecraftVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinecraftVersionInfo($$parsedSource as Partial<MinecraftVersionInfo>);
    }
}
