// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as minecraft$0 from "../minecraft/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChooseDirectory(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2005924590) as any;
    return $resultPromise;
}

export function DeleteAccount(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1544826504, id) as any;
    return $resultPromise;
}

export function GetAccounts(): Promise<$models.AccountsInfo> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4204191442) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetInstalledVersion(): Promise<minecraft$0.MinecraftVersionInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2395660188) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetLastPlayedVersion(): Promise<minecraft$0.MinecraftVersionInfo | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3471726875) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetLauncherSettings(): Promise<$models.LauncherSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1348876603) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetLauncherVersion(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2334230546) as any;
    return $resultPromise;
}

export function GetMinecraftVersions(): Promise<minecraft$0.MinecraftVersionInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2693999292) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetTotalRAM(): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1130104332) as any;
    return $resultPromise;
}

export function OpenMinecraftDirectory(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4172241556) as any;
    return $resultPromise;
}

export function SaveLauncherSettings(settings: $models.LauncherSettings): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(873484414, settings) as any;
    return $resultPromise;
}

export function SelectAccount(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(105847305, id) as any;
    return $resultPromise;
}

export function SetApp(app: application$0.App | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1425406301, app) as any;
    return $resultPromise;
}

export function StartMinecraft(version: minecraft$0.MinecraftVersionInfo): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3976339689, version) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.AccountsInfo.createFrom;
const $$createType1 = minecraft$0.MinecraftVersionInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
const $$createType4 = $models.LauncherSettings.createFrom;
