// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function AddFreeAccount(username: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4125843922, username) as any;
    return $resultPromise;
}

export function AddMicrosoftAccount(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(437267646) as any;
    return $resultPromise;
}

export function SetApp(app: application$0.App | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4061598497, app) as any;
    return $resultPromise;
}
