// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function GetInstalledVersion() {
  return window['go']['main']['App']['GetInstalledVersion']();
}

export function GetLastPlayedVersion() {
  return window['go']['main']['App']['GetLastPlayedVersion']();
}

export function GetLauncherSettings() {
  return window['go']['main']['App']['GetLauncherSettings']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetMinecraftVersions() {
  return window['go']['main']['App']['GetMinecraftVersions']();
}

export function GetTotalRAM() {
  return window['go']['main']['App']['GetTotalRAM']();
}

export function OpenMinecraftDirectory() {
  return window['go']['main']['App']['OpenMinecraftDirectory']();
}

export function SaveLauncherSettings(arg1) {
  return window['go']['main']['App']['SaveLauncherSettings'](arg1);
}

export function StartMinecraft(arg1) {
  return window['go']['main']['App']['StartMinecraft'](arg1);
}
