// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {minecraft} from '../models';
import {main} from '../models';

export function ChooseDirectory():Promise<string>;

export function GetInstalledVersion():Promise<Array<minecraft.MinecraftVersionInfo>>;

export function GetLastPlayedVersion():Promise<minecraft.MinecraftVersionInfo>;

export function GetLauncherSettings():Promise<main.LauncherSettings>;

export function GetLauncherVersion():Promise<string>;

export function GetMinecraftVersions():Promise<Array<minecraft.MinecraftVersionInfo>>;

export function GetTotalRAM():Promise<number>;

export function OpenMinecraftDirectory():Promise<void>;

export function SaveLauncherSettings(arg1:main.LauncherSettings):Promise<void>;

export function StartMinecraft(arg1:main.StartOptions):Promise<void>;
