# name: Build & Release Launcher

# on:
#   push:
#     tags:
#       - "v*"

# jobs:
#   build:
#     name: Build on Windows
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: "1.23"

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22.14"

#       - name: Install Wails CLI
#         run: go install github.com/wailsapp/wails/v3/cmd/wails@latest

#       - name: Build Wails app
#         run: wails build

#       - name: Archive release
#         run: |
#           Compress-Archive -Path .\bin\launcher.exe -DestinationPath launcher.zip

#       - name: Create GitHub Release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: launcher.zip
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
